# Generated by Django 5.2.15 on 2026-06-17 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('api_id', models.IntegerField(unique=True, verbose_name='ID в OpenWeather')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название поездки')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.city')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.trip')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='cities',
            field=models.ManyToManyField(related_name='trips', through='weather.TripCity', to='weather.city'),
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата прогноза')),
                ('temp', models.FloatField(verbose_name='Температура (°C)')),
                ('humidity', models.IntegerField(verbose_name='Влажность (%)')),
                ('wind_speed', models.FloatField(verbose_name='Скорость ветра (м/с)')),
                ('description', models.CharField(max_length=200, verbose_name='Описание погоды')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='weather.city')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('city', 'date')},
            },
        ),
    ]
