# Generated by Django 5.2.15 on 2026-06-17 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripcity',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='tripcity',
            name='city',
        ),
        migrations.CreateModel(
            name='ComfortRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('comfort_index', models.FloatField(verbose_name='Индекс комфорта')),
                ('rating', models.CharField(choices=[('excellent', 'Отлично'), ('good', 'Хорошо'), ('average', 'Средне'), ('poor', 'Плохо')], max_length=20, verbose_name='Оценка')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.city', verbose_name='Город')),
                ('weather_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comfort', to='weather.weatherrecord', verbose_name='Запись погоды')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('city', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='TripCity',
        ),
    ]
